# Data parameters
data:
  seed: 777
  batch_size: 1
  imgA_path: 'images/monet.jpg'
  imgB_path: 'images/forest.jpg'
  img_size: [128, 128]

# Model parameters
model:
  gen_input_dim: 3
  gen_output_dim: 3
  dis_input_dim: 3
  dis_conv_filters: [16,32,64,128]
  dis_conv_kernels: [3,3,3,3]
  dis_conv_strides: [2,2,2,1]
  dis_conv_pads: [1,1,1,1]
  dis_norm: [False, True, True, True]

# Training parameters
train:
  epochs: 100
  lr: 0.0002
  betas: [0.5, 0.999]

# Save
save:
  model_name: 'style_transfer'

# Other parameters
others:
  log_period: 10